### ISSUE TITLE
Problems using d3.js with cartero

### ISSUE THREAD

**Issue by ferlores** [rotundasoftware/cartero#50]
Hi @dgbeck 
I'm trying to use d3.js through cartero and I'm getting some errors. I believe it is because d3.js package.json is defining a browserify key here:
https://github.com/mbostock/d3/blob/master/package.json#L29

I also noticed that cartero is doing the following: https://github.com/rotundasoftware/cartero/blob/master/index.js#L225

I'm not sure about what is browserify expecting in general and if the bug is on d3.js code or in cartero. Do you mind looking at it? I'm happy to prepara a PR once we can diagnose what is the right solution
Thanks!
F

**Comment by dgbeck** [comment]
Hi @ferlores ,

Do you have an exact error message?

I think the problem might be in the package.json definition, since far as I can determine from a quick poke around, the `browserify` key in package.json should be an object, not a string.

https://github.com/substack/node-browserify#browserifytransform

It looks like somebody may have confused that key with the "browser" key:

https://github.com/substack/node-browserify#browser-field

**Comment by ferlores** [comment]
Thanks Dave, I created a PR in D3. I hope they merge it in soon: https://github.com/mbostock/d3/pull/2708

Thanks!
